{% set name = "python-graphblas" %}
{% set version = "2023.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-graphblas-{{ version }}.tar.gz
  sha256: 5754d9c41aae70416b4f5f9af07a7e0aa10497d5895f4da06921eafb3f6ca669

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python
    - python-suitesparse-graphblas >=7.4.0.0,<9
    - numpy >=1.21
    - numba >=0.55  # [py<312]
    - donfig >=0.6
    - pyyaml >=5.4

test:
  imports:
    - graphblas
    - graphblas.agg
  commands:
    - pip check
    - python -c "from graphblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/python-graphblas/python-graphblas
  summary: 'Python library for GraphBLAS: high-performance sparse linear algebra for scalable graph analytics'
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be a Pythonic way to write beautiful, efficient graph algorithms
    in the language of linear algebra.
  dev_url: https://github.com/python-graphblas/python-graphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
