{% set name = "python-graphblas" %}
{% set version = "2025.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_graphblas-{{ version }}.tar.gz
  sha256: 63e4cabc7c8fe90b5f61b13b2d32682f3480f13c994b7f186c15905e27682664

build:
  noarch: python
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python
    - python-suitesparse-graphblas >=7.4.0.0,<10
    - numpy >=1.23
    - numba >=0.55
    - donfig >=0.6
    - pyyaml >=5.4

test:
  imports:
    - graphblas
    - graphblas.agg
  commands:
    - pip check
    - python -c "from graphblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/python-graphblas/python-graphblas
  summary: 'Python library for GraphBLAS: high-performance sparse linear algebra for scalable graph analytics'
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be a Pythonic way to write beautiful, efficient graph algorithms
    in the language of linear algebra.
  dev_url: https://github.com/python-graphblas/python-graphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
